### PR TITLE
Fix message processing

### LINKED ISSUE #254: v2.11.2 Autoliking no longer functions
Issue traced to message processing

### PR DESCRIPTION
**Pull request by RaceProUK**
Fixes #254

Emergency fix, hence version number increase

### CODE REVIEW

File: lib/messages.js [hunk 1]
```diff
@@ -163,7 +163,7 @@ function handleMessages(messages) {
         privateFns.processPosts(postMessages, next);
     }], (_, finalMessages) => {
         finalMessages.forEach(message => {
-            const handled = internals.events.emit('topic#' + message.topic.topic_id,
```
Comment (AccaliaDeElementia) [inline lib/messages.js]: :headdesk:

really?

BAD @AccaliaDeElementia!

Comment (RaceProUK) [inline lib/messages.js]: I've made that mistake so many times :wink:
